export const el = {
  frame: document.getElementById('frame'),
  board: document.getElementById('board'),
  boardContent: document.getElementById('board-content'),
  apikey: document.getElementById('apikey'),
  req: document.getElementById('req'),
  image: document.getElementById('image'),
  imageChip: document.getElementById('image-chip'),
  voiceChip: document.getElementById('voice-chip'),
  chatLog: document.getElementById('chat-log'),
  status: document.getElementById('status-bar'),
  goBtn: document.getElementById('go-btn'),
  eraseBtn: document.getElementById('erase-btn'),
  autoTalkBtn: document.getElementById('auto-talk-btn'),
  resizeHandle: document.getElementById('resize-handle'),
  wRange: document.getElementById('w-range'),
  hRange: document.getElementById('h-range'),
  wVal: document.getElementById('w-val'),
  hVal: document.getElementById('h-val'),
  sizeReset: document.getElementById('size-reset'),
};
